from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

APP_NAME = os.getenv("APP_NAME", "Dual Momentum")
APP_ENV = os.getenv("APP_ENV", "development")

DATABASE_PATH = os.getenv("DATABASE_PATH", "data/dual_momentum.db")

UNIVERSE_EXCEL_PATH = os.getenv("UNIVERSE_EXCEL_PATH", "data/reference/nifty500_universe.xlsx")
UNIVERSE_JSON_PATH = os.getenv("UNIVERSE_JSON_PATH", "data/reference/nifty500_universe.json")
UNIVERSE_VALIDATION_REPORT_PATH = os.getenv(
    "UNIVERSE_VALIDATION_REPORT_PATH",
    "data/output/universe_validation_report.json",
)

LOG_DIR = os.getenv("LOG_DIR", "logs")

DEFAULT_BENCHMARK_SYMBOL = os.getenv("DEFAULT_BENCHMARK_SYMBOL", "NIFTY500")
LIQUIDBEES_SYMBOL = os.getenv("LIQUIDBEES_SYMBOL", "LIQUIDBEES")
MARKET_DATA_PROVIDER = os.getenv("MARKET_DATA_PROVIDER", "KITE")
YAHOO_SYMBOL_SUFFIX = os.getenv("YAHOO_SYMBOL_SUFFIX", ".NS")
YAHOO_BENCHMARK_SYMBOL = os.getenv("YAHOO_BENCHMARK_SYMBOL", "^CRSLDX")
KITE_API_KEY = os.getenv("KITE_API_KEY", "")
KITE_ACCESS_TOKEN = os.getenv("KITE_ACCESS_TOKEN", "")
KITE_ACCESS_TOKEN_DATE = os.getenv("KITE_ACCESS_TOKEN_DATE", "")
KITE_EXCHANGE = os.getenv("KITE_EXCHANGE", "NSE")
KITE_BENCHMARK_TRADINGSYMBOL = os.getenv("KITE_BENCHMARK_TRADINGSYMBOL", "NIFTY 500")
KITE_HISTORICAL_DAY_CHUNK_DAYS = int(os.getenv("KITE_HISTORICAL_DAY_CHUNK_DAYS", "1900"))
KITE_REQUEST_SLEEP_SECONDS = float(os.getenv("KITE_REQUEST_SLEEP_SECONDS", "0.4"))
KITE_MAX_RETRIES = int(os.getenv("KITE_MAX_RETRIES", "5"))
KITE_RETRY_BACKOFF_SECONDS = float(os.getenv("KITE_RETRY_BACKOFF_SECONDS", "2.0"))

MAX_STOCK_WEIGHT = float(os.getenv("MAX_STOCK_WEIGHT", "0.05"))
HIGH_52W_THRESHOLD = float(os.getenv("HIGH_52W_THRESHOLD", "0.80"))
BETA_LOOKBACK_DAYS = int(os.getenv("BETA_LOOKBACK_DAYS", "252"))
BETA_FLOOR = float(os.getenv("BETA_FLOOR", "0.25"))

COOLDOWN_CHECK_EVERY_RESHUFFLES = int(os.getenv("COOLDOWN_CHECK_EVERY_RESHUFFLES", "6"))
COOLDOWN_DURATION_MONTHS = int(os.getenv("COOLDOWN_DURATION_MONTHS", "1"))
PORTFOLIO_EMA_PERIOD_MONTHS = int(os.getenv("PORTFOLIO_EMA_PERIOD_MONTHS", "6"))

DEFAULT_MODE = os.getenv("DEFAULT_MODE", "RANK_ONLY")


def ensure_runtime_directories() -> None:
    for path in [
        Path(DATABASE_PATH).parent,
        Path(UNIVERSE_JSON_PATH).parent,
        Path(UNIVERSE_VALIDATION_REPORT_PATH).parent,
        Path(LOG_DIR),
    ]:
        path.mkdir(parents=True, exist_ok=True)


def public_config() -> dict[str, str | int | float]:
    return {
        "APP_NAME": APP_NAME,
        "APP_ENV": APP_ENV,
        "DATABASE_PATH": DATABASE_PATH,
        "UNIVERSE_EXCEL_PATH": UNIVERSE_EXCEL_PATH,
        "UNIVERSE_JSON_PATH": UNIVERSE_JSON_PATH,
        "UNIVERSE_VALIDATION_REPORT_PATH": UNIVERSE_VALIDATION_REPORT_PATH,
        "LOG_DIR": LOG_DIR,
        "DEFAULT_BENCHMARK_SYMBOL": DEFAULT_BENCHMARK_SYMBOL,
        "LIQUIDBEES_SYMBOL": LIQUIDBEES_SYMBOL,
        "MARKET_DATA_PROVIDER": MARKET_DATA_PROVIDER,
        "YAHOO_SYMBOL_SUFFIX": YAHOO_SYMBOL_SUFFIX,
        "YAHOO_BENCHMARK_SYMBOL": YAHOO_BENCHMARK_SYMBOL,
        "KITE_EXCHANGE": KITE_EXCHANGE,
        "KITE_BENCHMARK_TRADINGSYMBOL": KITE_BENCHMARK_TRADINGSYMBOL,
        "KITE_HISTORICAL_DAY_CHUNK_DAYS": KITE_HISTORICAL_DAY_CHUNK_DAYS,
        "KITE_REQUEST_SLEEP_SECONDS": KITE_REQUEST_SLEEP_SECONDS,
        "KITE_MAX_RETRIES": KITE_MAX_RETRIES,
        "KITE_RETRY_BACKOFF_SECONDS": KITE_RETRY_BACKOFF_SECONDS,
        "MAX_STOCK_WEIGHT": MAX_STOCK_WEIGHT,
        "HIGH_52W_THRESHOLD": HIGH_52W_THRESHOLD,
        "BETA_LOOKBACK_DAYS": BETA_LOOKBACK_DAYS,
        "BETA_FLOOR": BETA_FLOOR,
        "COOLDOWN_CHECK_EVERY_RESHUFFLES": COOLDOWN_CHECK_EVERY_RESHUFFLES,
        "COOLDOWN_DURATION_MONTHS": COOLDOWN_DURATION_MONTHS,
        "PORTFOLIO_EMA_PERIOD_MONTHS": PORTFOLIO_EMA_PERIOD_MONTHS,
        "DEFAULT_MODE": DEFAULT_MODE,
    }
