from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

APP_NAME = os.getenv("APP_NAME", "Strategy Research Factory")
APP_ENV = os.getenv("APP_ENV", "development")
STRATEGY_PROFILE_PATH = os.getenv("STRATEGY_PROFILE_PATH", "strategies/dual-momentum/strategy_profile.json")

DATABASE_PATH = os.getenv("DATABASE_PATH", "data/research_factory.db")

UNIVERSE_EXCEL_PATH = os.getenv("UNIVERSE_EXCEL_PATH", "data/reference/nifty500_universe.xlsx")
UNIVERSE_JSON_PATH = os.getenv("UNIVERSE_JSON_PATH", "data/reference/nifty500_universe.json")
UNIVERSE_VALIDATION_REPORT_PATH = os.getenv(
    "UNIVERSE_VALIDATION_REPORT_PATH",
    "data/output/universe_validation_report.json",
)

LOG_DIR = os.getenv("LOG_DIR", "logs")

DEFAULT_BENCHMARK_SYMBOL = os.getenv("DEFAULT_BENCHMARK_SYMBOL", "NIFTY500")
LIQUIDBEES_SYMBOL = os.getenv("LIQUIDBEES_SYMBOL", "LIQUIDBEES")
SAFE_ASSET_SYMBOL = os.getenv("SAFE_ASSET_SYMBOL", LIQUIDBEES_SYMBOL).strip().upper()
SAFE_ASSET_SYMBOLS = sorted(
    {
        symbol.strip().upper()
        for symbol in os.getenv("SAFE_ASSET_SYMBOLS", SAFE_ASSET_SYMBOL).split(",")
        if symbol.strip()
    }
)
MARKET_DATA_PROVIDER = os.getenv("MARKET_DATA_PROVIDER", "KITE")
YAHOO_SYMBOL_SUFFIX = os.getenv("YAHOO_SYMBOL_SUFFIX", ".NS")
YAHOO_BENCHMARK_SYMBOL = os.getenv("YAHOO_BENCHMARK_SYMBOL", "^CRSLDX")
MAX_PRICE_FORWARD_FILL_DAYS = int(os.getenv("MAX_PRICE_FORWARD_FILL_DAYS", "5"))
KITE_API_KEY = os.getenv("KITE_API_KEY", "")
KITE_ACCESS_TOKEN = os.getenv("KITE_ACCESS_TOKEN", "")
KITE_ACCESS_TOKEN_DATE = os.getenv("KITE_ACCESS_TOKEN_DATE", "")
KITE_EXCHANGE = os.getenv("KITE_EXCHANGE", "NSE")
KITE_BENCHMARK_TRADINGSYMBOL = os.getenv("KITE_BENCHMARK_TRADINGSYMBOL", "NIFTY 500")
KITE_HISTORICAL_DAY_CHUNK_DAYS = int(os.getenv("KITE_HISTORICAL_DAY_CHUNK_DAYS", "1900"))
KITE_REQUEST_TIMEOUT_SECONDS = int(os.getenv("KITE_REQUEST_TIMEOUT_SECONDS", "30"))
KITE_REQUEST_SLEEP_SECONDS = float(os.getenv("KITE_REQUEST_SLEEP_SECONDS", "0.4"))
KITE_MAX_RETRIES = int(os.getenv("KITE_MAX_RETRIES", "5"))
KITE_RETRY_BACKOFF_SECONDS = float(os.getenv("KITE_RETRY_BACKOFF_SECONDS", "2.0"))
SELENIUM_LOGIN_TIMEOUT_SECONDS = int(os.getenv("SELENIUM_LOGIN_TIMEOUT_SECONDS", "180"))

MAX_STOCK_WEIGHT = float(os.getenv("MAX_STOCK_WEIGHT", "0.05"))
MAX_SECTOR_WEIGHT = float(os.getenv("MAX_SECTOR_WEIGHT", "1.0"))
HIGH_52W_THRESHOLD = float(os.getenv("HIGH_52W_THRESHOLD", "0.80"))
BETA_LOOKBACK_DAYS = int(os.getenv("BETA_LOOKBACK_DAYS", "252"))
BETA_FLOOR = float(os.getenv("BETA_FLOOR", "0.25"))
MOMENTUM_SKIP_RECENT_DAYS = int(os.getenv("MOMENTUM_SKIP_RECENT_DAYS", "21"))
STRATEGY_RANKING_METHOD = os.getenv("STRATEGY_RANKING_METHOD", "AVERAGE_RANK").strip().upper()
RANKING_MOMENTUM_WEIGHT = float(os.getenv("RANKING_MOMENTUM_WEIGHT", "0.60"))
RANKING_BETA_WEIGHT = float(os.getenv("RANKING_BETA_WEIGHT", "0.25"))
RANKING_VOLATILITY_WEIGHT = float(os.getenv("RANKING_VOLATILITY_WEIGHT", "0.15"))
STRATEGY_ALLOCATION_MODE = os.getenv("STRATEGY_ALLOCATION_MODE", "TOP_N_EQUAL").strip().upper()
STRATEGY_TOP_N = int(os.getenv("STRATEGY_TOP_N", "25"))
BUFFER_PCT = float(os.getenv("BUFFER_PCT", "0"))
DYNAMIC_MIN_WEIGHT = float(os.getenv("DYNAMIC_MIN_WEIGHT", "0.01"))
DYNAMIC_MAX_WEIGHT = float(os.getenv("DYNAMIC_MAX_WEIGHT", "0.07"))
BACKTEST_REBALANCES_PER_MONTH = int(os.getenv("BACKTEST_REBALANCES_PER_MONTH", "1"))
BACKTEST_REUSE_SCENARIO = os.getenv("BACKTEST_REUSE_SCENARIO", "true").strip().lower() in {"1", "true", "yes", "y"}
AUTO_REBALANCE_TARGET_DAYS = os.getenv("AUTO_REBALANCE_TARGET_DAYS", "1,15")
AUTOMATION_HISTORY_LOOKBACK_DAYS = int(os.getenv("AUTOMATION_HISTORY_LOOKBACK_DAYS", "10"))
TARGET_PORTFOLIO_VALUE = float(os.getenv("TARGET_PORTFOLIO_VALUE", "1000000"))
AVAILABLE_PURCHASE_FUNDS = float(os.getenv("AVAILABLE_PURCHASE_FUNDS", str(TARGET_PORTFOLIO_VALUE)))

COOLDOWN_CHECK_EVERY_RESHUFFLES = int(os.getenv("COOLDOWN_CHECK_EVERY_RESHUFFLES", "6"))
COOLDOWN_DURATION_MONTHS = int(os.getenv("COOLDOWN_DURATION_MONTHS", "1"))
PORTFOLIO_EMA_PERIOD_MONTHS = int(os.getenv("PORTFOLIO_EMA_PERIOD_MONTHS", "6"))

DEFAULT_MODE = os.getenv("DEFAULT_MODE", "RANK_ONLY")

STRATEGY_PACKAGE_OUTPUT_DIR = os.getenv(
    "STRATEGY_PACKAGE_OUTPUT_DIR",
    "data/output/packages/dual-momentum/strategy-package",
)
STRATEGY_PACKAGE_VERSION = os.getenv("STRATEGY_PACKAGE_VERSION", "1.0.0")
STRATEGY_PACKAGE_ID = os.getenv("STRATEGY_PACKAGE_ID", "dual_momentum_nifty500_v1")
STRATEGY_PACKAGE_SLUG = os.getenv("STRATEGY_PACKAGE_SLUG", "dual-momentum")
STRATEGY_PACKAGE_NAME = os.getenv("STRATEGY_PACKAGE_NAME", APP_NAME)
STRATEGY_PACKAGE_SHORT_DESCRIPTION = os.getenv(
    "STRATEGY_PACKAGE_SHORT_DESCRIPTION",
    "A Nifty 500 rules-based momentum model portfolio with built-in diversification and risk controls.",
)
STRATEGY_PACKAGE_CATEGORY_LABELS = os.getenv(
    "STRATEGY_PACKAGE_CATEGORY_LABELS",
    "Momentum,Factor Strategy,Equity,Model Portfolio",
)
STRATEGY_PACKAGE_RA_ENTITY = os.getenv("STRATEGY_PACKAGE_RA_ENTITY", "Prathamesh Gupta")
STRATEGY_PACKAGE_SEBI_REGISTRATION_NUMBER = os.getenv("STRATEGY_PACKAGE_SEBI_REGISTRATION_NUMBER", "")
STRATEGY_PACKAGE_UNIVERSE = os.getenv("STRATEGY_PACKAGE_UNIVERSE", "NIFTY 500")
STRATEGY_PACKAGE_BENCHMARK = os.getenv("STRATEGY_PACKAGE_BENCHMARK", "NIFTY 500 TRI")
STRATEGY_PACKAGE_BASE_CURRENCY = os.getenv("STRATEGY_PACKAGE_BASE_CURRENCY", "INR")
STRATEGY_PACKAGE_MIN_CAPITAL_GUIDANCE = int(os.getenv("STRATEGY_PACKAGE_MIN_CAPITAL_GUIDANCE", "0"))
STRATEGY_PUBLIC_METHODOLOGY_PATH = os.getenv(
    "STRATEGY_PUBLIC_METHODOLOGY_PATH",
    "strategies/dual-momentum/methodology.md",
)
STRATEGY_INTERNAL_METHODOLOGY_PATH = os.getenv(
    "STRATEGY_INTERNAL_METHODOLOGY_PATH",
    "strategies/dual-momentum/methodology_internal.md",
)
OPTIMIZATION_RESULTS_PATH = os.getenv(
    "OPTIMIZATION_RESULTS_PATH",
    "data/output/average_rank_buffer_10y_trials_parameters_cagr.csv",
)
FINALIZED_STRATEGY_CONFIG_PATH = os.getenv(
    "FINALIZED_STRATEGY_CONFIG_PATH",
    "data/output/finalized/dual_momentum_best_config.json",
)
OPTIMIZATION_ENGINE_PATH = os.getenv(
    "OPTIMIZATION_ENGINE_PATH",
    "strategies/dual-momentum/experiments/optimizer.py",
)
OPTIMIZATION_ENGINE_MODULE = os.getenv(
    "OPTIMIZATION_ENGINE_MODULE",
    "",
)


def ensure_runtime_directories() -> None:
    for path in [
        Path(DATABASE_PATH).parent,
        Path(UNIVERSE_JSON_PATH).parent,
        Path(UNIVERSE_VALIDATION_REPORT_PATH).parent,
        Path(LOG_DIR),
    ]:
        path.mkdir(parents=True, exist_ok=True)


def public_config() -> dict[str, str | int | float]:
    return {
        "APP_NAME": APP_NAME,
        "APP_ENV": APP_ENV,
        "STRATEGY_PROFILE_PATH": STRATEGY_PROFILE_PATH,
        "DATABASE_PATH": DATABASE_PATH,
        "UNIVERSE_EXCEL_PATH": UNIVERSE_EXCEL_PATH,
        "UNIVERSE_JSON_PATH": UNIVERSE_JSON_PATH,
        "UNIVERSE_VALIDATION_REPORT_PATH": UNIVERSE_VALIDATION_REPORT_PATH,
        "LOG_DIR": LOG_DIR,
        "DEFAULT_BENCHMARK_SYMBOL": DEFAULT_BENCHMARK_SYMBOL,
        "LIQUIDBEES_SYMBOL": LIQUIDBEES_SYMBOL,
        "SAFE_ASSET_SYMBOL": SAFE_ASSET_SYMBOL,
        "SAFE_ASSET_SYMBOLS": ",".join(SAFE_ASSET_SYMBOLS),
        "MARKET_DATA_PROVIDER": MARKET_DATA_PROVIDER,
        "YAHOO_SYMBOL_SUFFIX": YAHOO_SYMBOL_SUFFIX,
        "YAHOO_BENCHMARK_SYMBOL": YAHOO_BENCHMARK_SYMBOL,
        "MAX_PRICE_FORWARD_FILL_DAYS": MAX_PRICE_FORWARD_FILL_DAYS,
        "KITE_EXCHANGE": KITE_EXCHANGE,
        "KITE_BENCHMARK_TRADINGSYMBOL": KITE_BENCHMARK_TRADINGSYMBOL,
        "KITE_HISTORICAL_DAY_CHUNK_DAYS": KITE_HISTORICAL_DAY_CHUNK_DAYS,
        "KITE_REQUEST_TIMEOUT_SECONDS": KITE_REQUEST_TIMEOUT_SECONDS,
        "KITE_REQUEST_SLEEP_SECONDS": KITE_REQUEST_SLEEP_SECONDS,
        "KITE_MAX_RETRIES": KITE_MAX_RETRIES,
        "KITE_RETRY_BACKOFF_SECONDS": KITE_RETRY_BACKOFF_SECONDS,
        "SELENIUM_LOGIN_TIMEOUT_SECONDS": SELENIUM_LOGIN_TIMEOUT_SECONDS,
        "MAX_STOCK_WEIGHT": MAX_STOCK_WEIGHT,
        "MAX_SECTOR_WEIGHT": MAX_SECTOR_WEIGHT,
        "HIGH_52W_THRESHOLD": HIGH_52W_THRESHOLD,
        "BETA_LOOKBACK_DAYS": BETA_LOOKBACK_DAYS,
        "BETA_FLOOR": BETA_FLOOR,
        "MOMENTUM_SKIP_RECENT_DAYS": MOMENTUM_SKIP_RECENT_DAYS,
        "STRATEGY_RANKING_METHOD": STRATEGY_RANKING_METHOD,
        "RANKING_MOMENTUM_WEIGHT": RANKING_MOMENTUM_WEIGHT,
        "RANKING_BETA_WEIGHT": RANKING_BETA_WEIGHT,
        "RANKING_VOLATILITY_WEIGHT": RANKING_VOLATILITY_WEIGHT,
        "STRATEGY_ALLOCATION_MODE": STRATEGY_ALLOCATION_MODE,
        "STRATEGY_TOP_N": STRATEGY_TOP_N,
        "BUFFER_PCT": BUFFER_PCT,
        "DYNAMIC_MIN_WEIGHT": DYNAMIC_MIN_WEIGHT,
        "DYNAMIC_MAX_WEIGHT": DYNAMIC_MAX_WEIGHT,
        "BACKTEST_REBALANCES_PER_MONTH": BACKTEST_REBALANCES_PER_MONTH,
        "BACKTEST_REUSE_SCENARIO": BACKTEST_REUSE_SCENARIO,
        "AUTO_REBALANCE_TARGET_DAYS": AUTO_REBALANCE_TARGET_DAYS,
        "AUTOMATION_HISTORY_LOOKBACK_DAYS": AUTOMATION_HISTORY_LOOKBACK_DAYS,
        "TARGET_PORTFOLIO_VALUE": TARGET_PORTFOLIO_VALUE,
        "AVAILABLE_PURCHASE_FUNDS": AVAILABLE_PURCHASE_FUNDS,
        "COOLDOWN_CHECK_EVERY_RESHUFFLES": COOLDOWN_CHECK_EVERY_RESHUFFLES,
        "COOLDOWN_DURATION_MONTHS": COOLDOWN_DURATION_MONTHS,
        "PORTFOLIO_EMA_PERIOD_MONTHS": PORTFOLIO_EMA_PERIOD_MONTHS,
        "DEFAULT_MODE": DEFAULT_MODE,
        "STRATEGY_PUBLIC_METHODOLOGY_PATH": STRATEGY_PUBLIC_METHODOLOGY_PATH,
        "STRATEGY_INTERNAL_METHODOLOGY_PATH": STRATEGY_INTERNAL_METHODOLOGY_PATH,
        "OPTIMIZATION_RESULTS_PATH": OPTIMIZATION_RESULTS_PATH,
        "FINALIZED_STRATEGY_CONFIG_PATH": FINALIZED_STRATEGY_CONFIG_PATH,
        "OPTIMIZATION_ENGINE_PATH": OPTIMIZATION_ENGINE_PATH,
        "OPTIMIZATION_ENGINE_MODULE": OPTIMIZATION_ENGINE_MODULE,
        "STRATEGY_PACKAGE_OUTPUT_DIR": STRATEGY_PACKAGE_OUTPUT_DIR,
    }
