from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

APP_NAME = os.getenv("APP_NAME", "Dual Momentum")
APP_ENV = os.getenv("APP_ENV", "development")

DATABASE_PATH = os.getenv("DATABASE_PATH", "data/dual_momentum.db")

UNIVERSE_EXCEL_PATH = os.getenv("UNIVERSE_EXCEL_PATH", "data/reference/nifty500_universe.xlsx")
UNIVERSE_JSON_PATH = os.getenv("UNIVERSE_JSON_PATH", "data/reference/nifty500_universe.json")
UNIVERSE_VALIDATION_REPORT_PATH = os.getenv(
    "UNIVERSE_VALIDATION_REPORT_PATH",
    "data/output/universe_validation_report.json",
)

LOG_DIR = os.getenv("LOG_DIR", "logs")

DEFAULT_BENCHMARK_SYMBOL = os.getenv("DEFAULT_BENCHMARK_SYMBOL", "NIFTY500")
LIQUIDBEES_SYMBOL = os.getenv("LIQUIDBEES_SYMBOL", "LIQUIDBEES")
MARKET_DATA_PROVIDER = os.getenv("MARKET_DATA_PROVIDER", "KITE")
YAHOO_SYMBOL_SUFFIX = os.getenv("YAHOO_SYMBOL_SUFFIX", ".NS")
YAHOO_BENCHMARK_SYMBOL = os.getenv("YAHOO_BENCHMARK_SYMBOL", "^CRSLDX")
KITE_API_KEY = os.getenv("KITE_API_KEY", "")
KITE_ACCESS_TOKEN = os.getenv("KITE_ACCESS_TOKEN", "")
KITE_ACCESS_TOKEN_DATE = os.getenv("KITE_ACCESS_TOKEN_DATE", "")
KITE_EXCHANGE = os.getenv("KITE_EXCHANGE", "NSE")
KITE_BENCHMARK_TRADINGSYMBOL = os.getenv("KITE_BENCHMARK_TRADINGSYMBOL", "NIFTY 500")
KITE_HISTORICAL_DAY_CHUNK_DAYS = int(os.getenv("KITE_HISTORICAL_DAY_CHUNK_DAYS", "1900"))
KITE_REQUEST_SLEEP_SECONDS = float(os.getenv("KITE_REQUEST_SLEEP_SECONDS", "0.4"))
KITE_MAX_RETRIES = int(os.getenv("KITE_MAX_RETRIES", "5"))
KITE_RETRY_BACKOFF_SECONDS = float(os.getenv("KITE_RETRY_BACKOFF_SECONDS", "2.0"))
SELENIUM_LOGIN_TIMEOUT_SECONDS = int(os.getenv("SELENIUM_LOGIN_TIMEOUT_SECONDS", "180"))

MAX_STOCK_WEIGHT = float(os.getenv("MAX_STOCK_WEIGHT", "0.05"))
HIGH_52W_THRESHOLD = float(os.getenv("HIGH_52W_THRESHOLD", "0.80"))
BETA_LOOKBACK_DAYS = int(os.getenv("BETA_LOOKBACK_DAYS", "252"))
BETA_FLOOR = float(os.getenv("BETA_FLOOR", "0.25"))
STRATEGY_RANKING_METHOD = os.getenv("STRATEGY_RANKING_METHOD", "COMBINED_RANK").strip().upper()
RANKING_MOMENTUM_WEIGHT = float(os.getenv("RANKING_MOMENTUM_WEIGHT", "0.60"))
RANKING_BETA_WEIGHT = float(os.getenv("RANKING_BETA_WEIGHT", "0.25"))
RANKING_VOLATILITY_WEIGHT = float(os.getenv("RANKING_VOLATILITY_WEIGHT", "0.15"))
STRATEGY_ALLOCATION_MODE = os.getenv("STRATEGY_ALLOCATION_MODE", "TOP_N_EQUAL").strip().upper()
STRATEGY_TOP_N = int(os.getenv("STRATEGY_TOP_N", "15"))
DYNAMIC_MIN_WEIGHT = float(os.getenv("DYNAMIC_MIN_WEIGHT", "0.01"))
DYNAMIC_MAX_WEIGHT = float(os.getenv("DYNAMIC_MAX_WEIGHT", "0.07"))
BACKTEST_REBALANCES_PER_MONTH = int(os.getenv("BACKTEST_REBALANCES_PER_MONTH", "1"))
AUTO_REBALANCE_TARGET_DAYS = os.getenv("AUTO_REBALANCE_TARGET_DAYS", "1,15")
AUTOMATION_HISTORY_LOOKBACK_DAYS = int(os.getenv("AUTOMATION_HISTORY_LOOKBACK_DAYS", "10"))
TARGET_PORTFOLIO_VALUE = float(os.getenv("TARGET_PORTFOLIO_VALUE", "1000000"))
AVAILABLE_PURCHASE_FUNDS = float(os.getenv("AVAILABLE_PURCHASE_FUNDS", str(TARGET_PORTFOLIO_VALUE)))

COOLDOWN_CHECK_EVERY_RESHUFFLES = int(os.getenv("COOLDOWN_CHECK_EVERY_RESHUFFLES", "6"))
COOLDOWN_DURATION_MONTHS = int(os.getenv("COOLDOWN_DURATION_MONTHS", "1"))
PORTFOLIO_EMA_PERIOD_MONTHS = int(os.getenv("PORTFOLIO_EMA_PERIOD_MONTHS", "6"))

DEFAULT_MODE = os.getenv("DEFAULT_MODE", "RANK_ONLY")


def ensure_runtime_directories() -> None:
    for path in [
        Path(DATABASE_PATH).parent,
        Path(UNIVERSE_JSON_PATH).parent,
        Path(UNIVERSE_VALIDATION_REPORT_PATH).parent,
        Path(LOG_DIR),
    ]:
        path.mkdir(parents=True, exist_ok=True)


def public_config() -> dict[str, str | int | float]:
    return {
        "APP_NAME": APP_NAME,
        "APP_ENV": APP_ENV,
        "DATABASE_PATH": DATABASE_PATH,
        "UNIVERSE_EXCEL_PATH": UNIVERSE_EXCEL_PATH,
        "UNIVERSE_JSON_PATH": UNIVERSE_JSON_PATH,
        "UNIVERSE_VALIDATION_REPORT_PATH": UNIVERSE_VALIDATION_REPORT_PATH,
        "LOG_DIR": LOG_DIR,
        "DEFAULT_BENCHMARK_SYMBOL": DEFAULT_BENCHMARK_SYMBOL,
        "LIQUIDBEES_SYMBOL": LIQUIDBEES_SYMBOL,
        "MARKET_DATA_PROVIDER": MARKET_DATA_PROVIDER,
        "YAHOO_SYMBOL_SUFFIX": YAHOO_SYMBOL_SUFFIX,
        "YAHOO_BENCHMARK_SYMBOL": YAHOO_BENCHMARK_SYMBOL,
        "KITE_EXCHANGE": KITE_EXCHANGE,
        "KITE_BENCHMARK_TRADINGSYMBOL": KITE_BENCHMARK_TRADINGSYMBOL,
        "KITE_HISTORICAL_DAY_CHUNK_DAYS": KITE_HISTORICAL_DAY_CHUNK_DAYS,
        "KITE_REQUEST_SLEEP_SECONDS": KITE_REQUEST_SLEEP_SECONDS,
        "KITE_MAX_RETRIES": KITE_MAX_RETRIES,
        "KITE_RETRY_BACKOFF_SECONDS": KITE_RETRY_BACKOFF_SECONDS,
        "SELENIUM_LOGIN_TIMEOUT_SECONDS": SELENIUM_LOGIN_TIMEOUT_SECONDS,
        "MAX_STOCK_WEIGHT": MAX_STOCK_WEIGHT,
        "HIGH_52W_THRESHOLD": HIGH_52W_THRESHOLD,
        "BETA_LOOKBACK_DAYS": BETA_LOOKBACK_DAYS,
        "BETA_FLOOR": BETA_FLOOR,
        "STRATEGY_RANKING_METHOD": STRATEGY_RANKING_METHOD,
        "RANKING_MOMENTUM_WEIGHT": RANKING_MOMENTUM_WEIGHT,
        "RANKING_BETA_WEIGHT": RANKING_BETA_WEIGHT,
        "RANKING_VOLATILITY_WEIGHT": RANKING_VOLATILITY_WEIGHT,
        "STRATEGY_ALLOCATION_MODE": STRATEGY_ALLOCATION_MODE,
        "STRATEGY_TOP_N": STRATEGY_TOP_N,
        "DYNAMIC_MIN_WEIGHT": DYNAMIC_MIN_WEIGHT,
        "DYNAMIC_MAX_WEIGHT": DYNAMIC_MAX_WEIGHT,
        "BACKTEST_REBALANCES_PER_MONTH": BACKTEST_REBALANCES_PER_MONTH,
        "AUTO_REBALANCE_TARGET_DAYS": AUTO_REBALANCE_TARGET_DAYS,
        "AUTOMATION_HISTORY_LOOKBACK_DAYS": AUTOMATION_HISTORY_LOOKBACK_DAYS,
        "TARGET_PORTFOLIO_VALUE": TARGET_PORTFOLIO_VALUE,
        "AVAILABLE_PURCHASE_FUNDS": AVAILABLE_PURCHASE_FUNDS,
        "COOLDOWN_CHECK_EVERY_RESHUFFLES": COOLDOWN_CHECK_EVERY_RESHUFFLES,
        "COOLDOWN_DURATION_MONTHS": COOLDOWN_DURATION_MONTHS,
        "PORTFOLIO_EMA_PERIOD_MONTHS": PORTFOLIO_EMA_PERIOD_MONTHS,
        "DEFAULT_MODE": DEFAULT_MODE,
    }
