from __future__ import annotations

PACKAGE_FILES = [
    "manifest.json",
    "backtest_metrics.json",
    "returns_daily.csv",
    "returns_monthly.csv",
    "returns_yearly.csv",
    "drawdowns.csv",
    "benchmark_returns.csv",
    "latest_model_portfolio.csv",
    "rebalance_history.csv",
    "holdings_history.csv",
    "sector_exposure.csv",
    "marketcap_exposure.csv",
    "methodology.md",
    "disclosures.md",
    "import_notes.md",
]

CSV_HEADERS = {
    "returns_daily.csv": ["strategy_id", "date", "return", "equity_curve"],
    "returns_monthly.csv": ["strategy_id", "year", "month", "return"],
    "returns_yearly.csv": ["strategy_id", "year", "return"],
    "drawdowns.csv": ["strategy_id", "date", "drawdown"],
    "benchmark_returns.csv": ["strategy_id", "date", "benchmark", "return", "equity_curve"],
    "latest_model_portfolio.csv": [
        "strategy_id",
        "as_of_date",
        "symbol",
        "company_name",
        "exchange",
        "isin",
        "sector",
        "marketcap_bucket",
        "target_weight",
        "reference_price",
        "entry_date",
        "notes",
    ],
    "rebalance_history.csv": [
        "strategy_id",
        "rebalance_date",
        "symbol",
        "company_name",
        "action",
        "old_weight",
        "new_weight",
        "old_reference_price",
        "new_reference_price",
        "rationale",
    ],
    "holdings_history.csv": [
        "strategy_id",
        "date",
        "symbol",
        "company_name",
        "exchange",
        "isin",
        "sector",
        "marketcap_bucket",
        "weight",
        "reference_price",
    ],
    "sector_exposure.csv": ["strategy_id", "as_of_date", "sector", "weight"],
    "marketcap_exposure.csv": ["strategy_id", "as_of_date", "marketcap_bucket", "weight"],
}
